owner: Nektiu-S-L 
repo: nektiu-products 

sites:
  - name: Nektiu
    url: https://nektiu.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://user-images.githubusercontent.com/11338137/160654176-ca34a78d-4cdf-4ec7-9ecf-f39d7276a6ab.png
  name: Nektiu Products Uptime
  introTitle: "**Uptime Monitoring page** for all Nektiu products"
  introMessage: For any urgent issues contact **clientes@nektiu.com** 
  navbar:
    - title: Status
      href: /
    - title: Nektiu
      href: https://nektiu.com/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
